apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sneha-webapp
  template:
    metadata:
      labels:
        app: sneha-webapp
    spec:
      containers:
      - name: sneha-webapp-container
        image: sneha-webapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080