apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: webapp-service   # Name of the resource
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 8080 and forward them to the targetPort of 8080
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: sneha-webapp        